version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"

